import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import ThemeSwitcher from "@/components/ThemeSwitcher";
import { Toaster } from "sonner";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={lexend.className}>
        <Toaster richColors closeButton position="bottom-right" />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
